################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c \
/Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_pwr.c 

OBJS += \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.o \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_pwr.o 

C_DEPS += \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.d \
./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_pwr.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_pwr.o: /Users/ming/STM32CubeIDE/workspace_1.10.1/FreeRTOS_Timers/Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_pwr.c Drivers/STM32G4xx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DSTM32G431xx -DUSE_HAL_DRIVER -DUSE_NUCLEO_64 -DDEBUG -c -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../../Inc -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../../Drivers/STM32G4xx_HAL_Driver/Inc -I../../Drivers/BSP/STM32G4xx_Nucleo -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Drivers-2f-STM32G4xx_HAL_Driver

clean-Drivers-2f-STM32G4xx_HAL_Driver:
	-$(RM) ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_cortex.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_dma_ex.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_exti.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ex.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_flash_ramfunc.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_gpio.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_pwr_ex.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_rcc_ex.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_tim_ex.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_hal_uart_ex.su ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_pwr.d ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_pwr.o ./Drivers/STM32G4xx_HAL_Driver/stm32g4xx_ll_pwr.su

.PHONY: clean-Drivers-2f-STM32G4xx_HAL_Driver

